version: "3.9"

services:
  api:
    build: .
    container_name: lease_analysis_api
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=1
    # For local dev with live reload, uncomment volumes and command
    # volumes:
    #   - ./app:/app/app:rw
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

